/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventanas;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import javax.swing.JOptionPane;
import proyecto2_Leon.AVL_Reserva;
import proyecto2_Leon.AVL_Historico;
import proyecto2_Leon.Estado;
import proyecto2_Leon.HashTableEstadoActual;
import proyecto2_Leon.Historico;
import proyecto2_Leon.ListaHabitacion;


public class AddClient extends javax.swing.JFrame {
    
    static HashTableEstadoActual Estado;
    static AVL_Reserva Reserva;
    static AVL_Historico Historico;
    static ListaHabitacion list_habitaciones;
    public AddClient(HashTableEstadoActual Estado, AVL_Reserva Reserva, AVL_Historico Historico, ListaHabitacion list_habitaciones) {
        initComponents();
        this.Estado = Estado;
        this.Reserva = Reserva;
        this.Historico = Historico;
        this.list_habitaciones = list_habitaciones;
        setLocationRelativeTo(null);

       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        gender = new javax.swing.ButtonGroup();
        tipoHabitacion = new javax.swing.ButtonGroup();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        simple = new javax.swing.JRadioButton();
        doble = new javax.swing.JRadioButton();
        triple = new javax.swing.JRadioButton();
        suite = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        InputAAAA = new javax.swing.JTextField();
        InputCelular = new javax.swing.JTextField();
        InputNombre = new javax.swing.JTextField();
        InputApellido = new javax.swing.JTextField();
        InputEmail = new javax.swing.JTextField();
        InputDD = new javax.swing.JTextField();
        InputMM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BackToMenu = new javax.swing.JButton();
        AddClient = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gender.add(Female);
        Female.setText("Female");
        getContentPane().add(Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        gender.add(Male);
        Male.setText("Male");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });
        getContentPane().add(Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        tipoHabitacion.add(simple);
        simple.setText("simple");
        getContentPane().add(simple, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        tipoHabitacion.add(doble);
        doble.setText("doble");
        getContentPane().add(doble, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, -1));

        tipoHabitacion.add(triple);
        triple.setText("triple");
        getContentPane().add(triple, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        tipoHabitacion.add(suite);
        suite.setText("suite");
        getContentPane().add(suite, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Elephant", 0, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR CLIENTES ACTUALES");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 450, 50));

        jLabel4.setBackground(new java.awt.Color(222, 222, 222));
        jLabel4.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("APELLIDO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 70, 30));

        jLabel5.setBackground(new java.awt.Color(222, 222, 222));
        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("/");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 30, 30));

        jLabel6.setBackground(new java.awt.Color(222, 222, 222));
        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, 30));

        jLabel7.setBackground(new java.awt.Color(222, 222, 222));
        jLabel7.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("HABITACION:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 90, 30));

        jLabel8.setBackground(new java.awt.Color(222, 222, 222));
        jLabel8.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("EMAIL:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, 30));

        jLabel9.setBackground(new java.awt.Color(222, 222, 222));
        jLabel9.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("GENERO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, 30));

        jLabel10.setBackground(new java.awt.Color(222, 222, 222));
        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("DD           MM          AAAA");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 160, 30));

        jLabel11.setBackground(new java.awt.Color(222, 222, 222));
        jLabel11.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("/");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 30, 30));

        jLabel12.setBackground(new java.awt.Color(222, 222, 222));
        jLabel12.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("LLEGADA:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 70, 30));

        jLabel13.setBackground(new java.awt.Color(222, 222, 222));
        jLabel13.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CELULAR:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 70, 30));

        InputAAAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputAAAAActionPerformed(evt);
            }
        });
        getContentPane().add(InputAAAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 70, 30));

        InputCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputCelularActionPerformed(evt);
            }
        });
        getContentPane().add(InputCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 120, 30));

        InputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputNombreActionPerformed(evt);
            }
        });
        getContentPane().add(InputNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, 30));

        InputApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(InputApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 120, 30));

        InputEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputEmailActionPerformed(evt);
            }
        });
        getContentPane().add(InputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 120, 30));

        InputDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputDDActionPerformed(evt);
            }
        });
        getContentPane().add(InputDD, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 30, 30));

        InputMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputMMActionPerformed(evt);
            }
        });
        getContentPane().add(InputMM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 30, 30));

        jLabel3.setBackground(new java.awt.Color(222, 222, 222));
        jLabel3.setFont(new java.awt.Font("Eras Bold ITC", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INGRESE LOS DATOS DEL CLIENTE A REGISTRAR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 440, 30));

        BackToMenu.setText("Volver");
        BackToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuActionPerformed(evt);
            }
        });
        getContentPane().add(BackToMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        AddClient.setText("Agregar Nuevo Cliente");
        AddClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddClientActionPerformed(evt);
            }
        });
        getContentPane().add(AddClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InputAAAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputAAAAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputAAAAActionPerformed

    private void BackToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MenuEstado menu = new MenuEstado(Estado, Reserva, Historico, list_habitaciones);
        menu.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BackToMenuActionPerformed

    private void AddClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddClientActionPerformed
       
        
        Male.setActionCommand("Male");
        Female.setActionCommand("Female");
        simple.setActionCommand("simple");
        doble.setActionCommand("doble");
        triple.setActionCommand("triple");
        suite.setActionCommand("suite");
        
        String nombre = InputNombre.getText();
        String apellido = InputApellido.getText();
        String email = InputEmail.getText();
        String celular = InputCelular.getText();
        
        if (!"".equals(nombre) & !"".equals(apellido) & !"".equals(email) & !"".equals(celular) & gender.getSelection() != null & tipoHabitacion.getSelection() != null){
            try {
                String genero = gender.getSelection().getActionCommand();
                
                String tha = tipoHabitacion.getSelection().getActionCommand();
                
                
                int dd = Integer.parseInt(InputDD .getText());
                int mm = Integer.parseInt(InputMM.getText());
                int aaaa = Integer.parseInt(InputAAAA.getText());
                int[] llegada = {dd, mm, aaaa};
                
                Estado cn = Estado.getEstado(nombre, apellido);
                
                
                
                if (cn == null){
                    
                    int num = list_habitaciones.buscar_habitacion(tha);
                    
                    Estado cliente_n = new Estado(num, nombre, apellido, email, genero, celular, llegada);
                    
                    int index1 = Estado.hashFunction(cliente_n);
                    
                    Estado.insertEstado(cliente_n, index1);
                    
                    
                    JOptionPane.showMessageDialog(null, "Cliente Registrado exitosamente!\n" +"Nombre: "+cliente_n.getNombre()+" "+ cliente_n.getApellido()+"\n"+"Email: "+cliente_n.getEmail()+"\n"+"Genero: "+cliente_n.getGender()+"\n"+"Celular: "+cliente_n.getCelular()+"\n"+"Llegada: "+cliente_n.getLlegada()[0]+"/"+cliente_n.getLlegada()[1]+"/"+cliente_n.getLlegada()[2]+"\n"+"Habitacion: "+ num);
                
                } else {
                    JOptionPane.showMessageDialog(null, "Error! El cliente con ese nombre ya esta registrado!");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error! Recuerde escribir solo valores numericos para la llegada!");
            }       
    }
        else{
            JOptionPane.showMessageDialog(null, "Error! recuerde en todos los campos y/o marcar todas las opciones!");
        }
    }//GEN-LAST:event_AddClientActionPerformed

    private void InputCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputCelularActionPerformed

    private void InputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputNombreActionPerformed

    private void InputApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputApellidoActionPerformed

    private void InputEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputEmailActionPerformed

    private void InputDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputDDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputDDActionPerformed

    private void InputMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InputMMActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
       // Male.setActionCommand("Male");
    }//GEN-LAST:event_MaleActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClient(Estado, Reserva, Historico, list_habitaciones).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddClient;
    private javax.swing.JButton BackToMenu;
    private javax.swing.JRadioButton Female;
    private javax.swing.JTextField InputAAAA;
    private javax.swing.JTextField InputApellido;
    private javax.swing.JTextField InputCelular;
    private javax.swing.JTextField InputDD;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputMM;
    private javax.swing.JTextField InputNombre;
    private javax.swing.JRadioButton Male;
    private javax.swing.JRadioButton doble;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton simple;
    private javax.swing.JRadioButton suite;
    private javax.swing.ButtonGroup tipoHabitacion;
    private javax.swing.JRadioButton triple;
    // End of variables declaration//GEN-END:variables
}
